### ISSUE TITLE
bots wont take chip and bot-topia help tab is not appearing in settings

### ISSUE THREAD

**Issue by Yellowface9** [LofiMonk/bot-topia#14]
**Describe the bug**
i am not understanding how to assign the bots their roles when i put the chip in their inventory they dont do nothing but look at me stupid :p ive also tried throwing it at them and using the interact button but it opens their inventory 

**To Reproduce**
to be fair i have many other mods included on my world these mods will be linked
[https://mcpedl.com/space-craft-addon/](https://mcpedl.com/space-craft-addon/)
[https://mcpedl.com/dungeon-craft-addon/](https://mcpedl.com/dungeon-craft-addon/)
[https://mcpedl.com/enderite-addon/](https://mcpedl.com/enderite-addon/)
[https://mcpedl.com/zgs-vanilla-structures-addon/](https://mcpedl.com/zgs-vanilla-structures-addon/)
[https://mcpedl.com/m1a2-abrams-tank-addon/](https://mcpedl.com/m1a2-abrams-tank-addon/)
[https://mcpedl.com/world-animals-addon/](https://mcpedl.com/world-animals-addon/)
[https://mcpedl.com/actualguns-3d/](https://mcpedl.com/actualguns-3d/) this one is a cause of another bug in its own right which removes the players arms
[https://mcpedl.com/portal-gun-add-on/](https://mcpedl.com/portal-gun-add-on/) this one is probably the cause of the help tab not appearing because it also has one
[https://mcpedl.com/vanilla-backpacks-addon/](https://mcpedl.com/vanilla-backpacks-addon/)
**Expected behavior**
the bot to take the chip and be assigned its role

**Minecraft (please complete the following information):**
 
 - Version 1.16.120
 **Bot-Topia**
- Version 1.0.12

**Additional context**
the chips i am attempting to use are the guard, miner, and farmer none are working and i do have farmland and seeds in the farmers inventory i am also using an xbox one hope this helps and thanks in advance

**Comment by LofiMonk** [comment]
After you turn your bot on with redstone you can click on it with a farmer, harvest, hopper chip. Give your bot legs and you can click on it with the guard, miner, lumber chips.
